version: "3"
services:
  nginx-app:
    container_name: mynginx2
    build:
      context: .
      dockerfile: dev.nginx.Dockerfile
    image: mynginx-demo:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    # privileged: true
    ports:
      - 85:80